package com.safelogisitics.gestionentreprisesusers.model.enums;

public enum EPrivilege {
  GESTION_UTILISATEURS,
  GESTION_AGENTS,
  GESTION_PRESTATAIRES,
  GESTION_ENTREPRISES,
  GESTION_CLIENTS,
  GESTION_TARIFS,
  GESTION_COMMANDE_LIVRAISONS,
  GESTION_COMMANDE_PRESTATIONS,
  GESTION_ABONNEMENTS,
  GESTION_TRANSACTIONS,
  GESTION_ENROLEMENTS
}