package com.safelogisitics.gestionentreprisesusers.model.enums;

public enum ESMSData {
  CLIENT_PRENOM,
  CLIENT_NOM,
  TRANSACTION_TYPE,
  TRANSACTION_MONTANT,
  ABONNEMENT_NUMERO_CARTE,
  ABONNEMENT_SOLDE,
  ABONNEMENT_SOLDE_PROGRESSIF,
  COMMANDE_NUMERO,
  COMMANDE_CODE_RETRAIT
}
